version: 2.1
orbs:
  # https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.0.0
  slack: circleci/slack@4.8.1
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      # - node/with-cache:
      #     steps:
      #       - run: npm install
            # - run: npm test
      # - slack/notify:
          # channel: channel_id
          # color: '#42e2f4'
          # mentions: 'foo,bar,'
          # message: This is a custom message notification
          # webhook: '${SLACK_WEBHOOK}'
workflows:
    build-and-test:
      jobs:
        - build-and-test
